version: 2.1

orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6

jobs:
  deploy-heroku:
    executor: heroku/default

    steps:
      - checkout

      - heroku/install

      - heroku/deploy-via-git:
          app-name: "joke-api-iw3"


workflows:
  deploy:
    jobs:
      - node/test:
          filters:
            branches:
              only:
              - circleci

      - node/run:
          npm-run: build
          filters:
            branches:
              only:
                - circleci

      - deploy-heroku:
          requires:
            - "node/test"
            - "node/run"
          filters:
            branches:
              only:
                - circleci