version: 2.1

orbs:
  node: circleci/node@5.0.2
  heroku: circleci/heroku@1.2.6
  docker: circleci/docker@2.1.3

workflows:
  build-test-deploy:
    jobs:
      - node/run:
          npm-run: build
          filters:
            branches:
              only:
                - circleci
                
      - node/test:
          filters:
            branches:
              only:
                - circleci

      - heroku/deploy-via-git:
          requires:
            - node/run
            - node/test
          app-name: "joke-app-iw4"
          filters:
            branches:
              only:
                - circleci

      - docker/publish:
          image: mohammaddocker/joke-api:latest
          docker-username: mohammaddocker
          docker-password: $DOCKER_PASSWORD
          requires:
            - node/run
            - node/test
          filters:
            branches:
              only:
                - circleci

  