apiVersion: apps/v1

kind: Deployment

metadata:
  name: joke-app

  labels:
    app: joke-app

spec:
  replicas: 3

  selector:
    matchLabels:
      app: joke-app

  template:
    metadata:
      labels:
        app: joke-app

    spec:
      containers:
        - name: joke-app

          image: mohammaddocker/joke-api:3.0.0
          env:
            - name: PORT
              value: "80"

          ports:
            - containerPort: 80
# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: joke-app
# spec:
#   selector:
#     app: joke-app
#   ports:
#     - port: 80
#       targetPort: 80
